// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqfygwenjpgaoidltuau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xZnlnd2VuanBnYW9pZGx0dWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NjUxNzcsImV4cCI6MjA3MDQ0MTE3N30.4GJkRgY11rqAR_NZUlJfvtvQSInrBt7BP6dKb9uM0Us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});